### PR TITLE
Make salts a first-class file of their own.

### LINKED ISSUE #124: Create wp-config: intermittent template error
Host: Mac OS X Mavericks

`wordpress | Create wp-config for {{ enviro }}` fails intermittently.  The string it fails at changes each time it fails.

A second provisioning run helps 99% of the time.

```
==> hgv: TASK: [wordpress | Create wp-config for php] **********************************
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
```

### PR DESCRIPTION
**Pull request by zamoose**
* [x] @zamoose
* [x] @markkelnar 

Fixes #124.

### CODE REVIEW

**Comment by zamoose** [comment]
@kevcenteno this is a bit of a mix of my approach and your approach. Try it out?

**Comment by kevcenteno** [comment]
@zamoose This looks good!

File: provisioning/roles/wordpress/templates/wp/wp-config.php [hunk 1]
```diff
@@ -54,7 +54,9 @@
 *
 * @since 2.6.0
 */
-{{ wpsalts.content }}
+if ( file_exists( dirname( __FILE__ ) . '/wp-salts.php' ) ) {
+    include( dirname( __FILE__ ) . '/wp-salts.php' );
```
Comment (shaneog) [inline provisioning/roles/wordpress/templates/wp/wp-config.php]: PHP included files need to have the PHP open tag (`<?php`) if they are to be interpreted as PHP. The Wordpress API does not include this opening tag, and thus the `wp-salts.php` file is not interpreted as PHP code.

Comment (shaneog) [inline provisioning/roles/wordpress/templates/wp/wp-config.php]: I added this task after `Fetch random salts for WordPress config` to fix it:
```yaml
- name: Make salts file a PHP file
  lineinfile:
    dest: "{{ wp_doc_root }}/{{ enviro }}/wp-salts.php"
    insertbefore: BOF
    line: <?php
```
I'm not sure if this can be combined with the `Fetch random salts for WordPress config` task

Comment (kevcenteno) [inline provisioning/roles/wordpress/templates/wp/wp-config.php]: +1

Comment (zamoose) [inline provisioning/roles/wordpress/templates/wp/wp-config.php]: You're 100% correct. Shazbot.

Comment (zamoose) [inline provisioning/roles/wordpress/templates/wp/wp-config.php]: @shaneog Integrated your fix into my patch. Looks good on my end -- provisions cleanly, sites seem to be good with the change.

**Comment by zamoose** [comment]
@markkelnar Ping on this one -- I've added @shaneog's suggested fix to the PR.

File: provisioning/roles/wordpress/tasks/main.yml [hunk 2]
```diff
@@ -23,10 +23,15 @@
   register: wpconfig
 
 - name: Fetch random salts for WordPress config
-  uri:
+  get_url:
+    dest: "{{ wp_doc_root }}/{{ enviro }}/wp-salts.php"
     url: https://api.wordpress.org/secret-key/1.1/salt/
-    return_content: yes
-  register: wpsalts
```
Comment (markkelnar) [inline provisioning/roles/wordpress/tasks/main.yml]: Should we do the get_url and lineinfile only when running the wp-config.php template below?  We have a 'when:' condition on that task.
```
when: not wpconfig.stat.exists

Comment (markkelnar) [inline provisioning/roles/wordpress/tasks/main.yml]: Ah, @zamoose is right, the get_url task will not run again if the dest file exists on disk.  Good deal.
